name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .  # Upload the whole project (current directory)

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
